In [ ]:
!pip install -qq tensorflow
!pip install -qq transformers
!pip install sentencepiece
!pip install torch==2.2.2
!pip install torchtext==0.17.2

In [ ]:
!pip install --upgrade torch

In [ ]:
!pip install --upgrade torch torchvision

In [ ]:
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer


In [ ]:
# Selecting the model. You will be using "facebook/blenderbot-400M-distill" in this example.
model_name = "facebook/blenderbot-400M-distill"

In [ ]:
# Load the model and tokenizer
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

pytorch_model.bin:   0%|          | 0.00/730M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/347 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/127k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/62.9k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/16.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/772 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/310k [00:00<?, ?B/s]

In [ ]:
# Define the chat function
def chat_with_bot():
    while True:
        # Get user input
        input_text = input("You: ")

        # Exit conditions
        if input_text.lower() in ["quit", "exit", "bye"]:
            print("Chatbot: Goodbye!")
            break

        # Tokenize input and generate response
        inputs = tokenizer.encode(input_text, return_tensors="pt")
        outputs = model.generate(inputs, max_new_tokens=150)
        response = tokenizer.decode(outputs[0], skip_special_tokens=True).strip()

        # Display bot's response
        print("Chatbot:", response)

# Start chatting
chat_with_bot()


You: Hello
Chatbot: Hi, how are you? I just got back from walking my dog. Do you have any pets?
You: No, I don't have any pets
Chatbot: Oh, I'm sorry to hear that. Do you have any hobbies that you like to do?
You: Yes, I do. My hobbis include riding bicycles
Chatbot: That's cool. I like to ride bikes too. What kind of bike do you ride?
You: I have a hybrid bike
Chatbot: What kind of bike is it? Is it a motorcycle or a bicycle?
You: It's a bicycle
Chatbot: What kind of bike is it? Is it a street bike or a motorcycle?
You: Street bike
Chatbot: Have you ever ridden a street bike? It's a type of motorized bicycle.
You: Oh, Id di not know that
Chatbot: I know, right?  I was so mad at myself.  I should have known better.
You: No worries
Chatbot: Do you have any advice on how to deal with it? I don't know what to do.
You: Bye
Chatbot: Goodbye!


In [7]:
from torch.utils.data import Dataset

In [27]:
sentences = ["If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.", "Fae's a ficle friend, Harry.", "Obi is a boy.", "Ada is a girl.", "Eze goes to school."]

In [28]:
class CustomDataset(Dataset):
  def __init__(self, sentences):
    self.sentences = sentences

  def __len__(self):
    return len(self.sentences)

  def __getitem__(self,idx):
    return self.sentences[idx]

In [29]:
my_dataset = CustomDataset(sentences)

In [30]:
my_dataset[0]

"If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals."

In [31]:
my_dataset[1]

"Fae's a ficle friend, Harry."

In [32]:
from torch.utils.data import DataLoader

In [33]:
custom_data = CustomDataset(sentences)

In [34]:
batch_size = 2

In [35]:
dataloader = DataLoader(custom_data, batch_size = batch_size, shuffle= True)

Instead of one sentences at a time (samples), data loaders can return them in batches, showing all the possibilities at once in the output

In [37]:
for batch in dataloader:
  print(batch)

["Fae's a ficle friend, Harry.", "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals."]
['Eze goes to school.', 'Obi is a boy.']
['Ada is a girl.']


the iter function outputs each batch using next function. Everytime one presses next(data_iter), it outputs the next batch until the last sample.

In [38]:
data_iter = iter(dataloader)

In [41]:
next(data_iter)

['Ada is a girl.']

In [ ]:
!pip install torchtext


In [50]:

import torch

In [ ]:
!pip install torchtext==0.15.1

In [1]:
from torch.nn.utils.rnn import pad_sequence
from torchtext.data.utils import get_tokenizer
from collections import Counter
from torchtext.vocab import Vocab

In [3]:
from torch.utils.data import Dataset

In [4]:
sentences = ["If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.", "Fae's a ficle friend, Harry.", "Obi is a boy.", "Ada is a girl.", "Eze goes to school.", "God is good."]

In [5]:
class CustomDataset(Dataset):
  def __init__(self, sentences):
    self.sentences = sentences

  def __len__(self):
    return len(self.sentences)

  def __getitem__(self,idx):
    return self.sentences[idx]

In [6]:
from torch.utils.data import DataLoader

In [7]:
custom_data = CustomDataset(sentences)

In [8]:
batch_size = 2

In [9]:
dataloader = DataLoader(custom_data, batch_size = batch_size, shuffle= True)

In [10]:
for batch in dataloader:
  print(batch)

["If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.", "Fae's a ficle friend, Harry."]
['Ada is a girl.', 'Eze goes to school.']
['Obi is a boy.', 'God is good.']


In [26]:
import torch
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import DataLoader, Dataset
from collections import Counter
from torchtext.vocab import Vocab
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

In [27]:
tokenizer = get_tokenizer("basic_english")

In [28]:
vocab = build_vocab_from_iterator(map(tokenizer, sentences))

In [29]:
from torch.nn.utils.rnn import pad_sequence

In [30]:
for batch in dataloader:
  padded_batch = pad_sequence(batch, batch_first= True, padding_value= 0)

In [31]:
def collate_fn(batch):
  tensor_batch = []
  for sample in batch:
    tokens = tokenizer(sample)
    tensor_batch.append(torch.tensor([vocab[token] for token in tokens]))
    padded_batch = pad_sequence(tensor_batch, batch_first = True)
    return padded_batch

In [32]:
dataloader = DataLoader(custom_data, batch_size= batch_size, shuffle= True, collate_fn= collate_fn)

In [33]:
for batch in dataloader:
  print(batch)

tensor([[13, 19,  8, 31,  0]])
tensor([[30,  3,  1, 11,  0]])
tensor([[18,  3,  5,  0]])
